src/semigroup/object.js, tests/funcadelic-test.js
Added a test and fix to ensure that prototype of left argument is maintained when appending objects.
The fix is only one line change but prettier went nuts on the test.
=> Make sure Semigroup maintains prototype of left argument

src/applicative/promise.js
When applying a function to a list of values, it the arguments are independent of each other, and so there is no need to explicity sequence them.
This allows the two promises to run in parallel and resolve in any order. In practice this won't make much difference, since we're not creating any new promises inside our function application, and _both_ have to be resolved in order to proceed, but at the very least it makes very clear that the evaluation of arguments for function application happens _in parallel_
=> Allow Promise application to run in parallel.

src/applicative.js, src/filterable.js, src/foldable.js, src/functor.js, src/monoid.js, src/semigroup.js, src/typeclasses.js
Funcadelic was using a kinda odd-ball mechanism to define typeclasses. This was so that you could use the typeclass name as a function to get the typeclass instance:
```javascript
Functor([]).map //=> gets the `map` method off of the specific
instance of Functor
```
While this is kind of clever, it turns out that you don't really ever need to get the instance except inside of the delegate, so it isn't really worth it.
This change puts all of the dispatch functions right on the class itself, and doesn't create a wrapper of any kind.
Inside typeclass methods, the typeclass instance can be accessed by calling the `this()` function. E.g.
```javascript
export const Functor = type(class Functor {
map(fn, f) {
let { map } = this(f);
return map(fn, f);
}
});
```
If you're outside of the typeclass …
=> Use normal classes for Typeclasses

.travis.yml, src/typeclasses.js
Node 6 doesn't support `Object.getOwnPropertyDescriptors`, so funcadelic can't be used there.
Instead of pulling off the function from `Object`, pull it in from `object.getownpropertydescriptors`
At the same time, fill in the matrix of node environments to include from 6-9
=> Polyfill getOwnPropertyDescriptors

src/applicative.js, src/applicative/promise.js
Previously, the Applicative instance was expected to have a method call `apply` that only applied a function to a single value. It then had a global function `apply` that utilized the instance `apply` to reduce an entire list one value at a time. That worked as long as there weren't any recursive values, but when you need to call back into the "single" value `apply` the names get confusing.
This separates out the single function that only appends two values together via function application. So the minimal implementation of applicative is now `applyOne`, and `apply` is what you call when you want to reduce a list of values via function application.
It also removes the monoid from the definition of `apply()`. While the application itself is in fact a monoid, it didn't lend any clarity to …
=> Disambiguate applicative instance apply and applyOne()

src/filterable/object.js, tests/funcadelic-test.js
I needed a way to map an immutable instance - so I ended up using `map` but in the process I found that filter changes class instances into objects. This PR maintains prototype of instances when applying filter to them.
Dunno if this is right, but you decide.
=> Maintain prototype in filter

src/functor/object.js, src/stable.js, tests/funcadelic-test.js
When you map an object like
```js
let mapped = map(x => x * 2, {one: 1, two: 2});
```
Because of the way that object map is implemented, every time you access the properties of mapped, the mapping function will be excuted every single time. For example:
```js
mapped.one
mapped.one
mapped.one
```
Will execute `x => x * 2` three times. But mapping is a pure function and so the answer can _never_ change between these three mappings, so it's pointless to execute it more than once. This is annoying not only from the perspective of computational work, but also from the perspective of referential transparency. In other words, if my mapping function is pure, it should return the same value every time, even if that is a reference value like `Object` or `Array`
What we'd like to do instead is only …
=> Make resulting values of an object map stable.

src/semigroup/object.js, src/stable.js, tests/funcadelic-test.js
This PR introduces caching to getters that are added to objects using `append`. 
```js
let combined = append({ two: 2, three: 3 }, {
get sum() {
return new Number(this.two + this.three);
}
});
combined.sum.valueOf() // => 5;
combined.sum === combined.sum
```
The sum calculation will only ever be performed once for any instance. All future invocations will produce previously computed value.
Note: this PR only caches the getters from the second argument.
Related to https://github.com/microstates/microstates.js/pull/81
=> Wrapping getters in thunk in append

package.json, rollup.config.js
Our UMD package includes ES6 features which breaks in IE11. This PR will change our UMD package to ES5.
=> Make sure UMD build is ES5

src/foldable/object.js, src/semigroup/object.js, tests/funcadelic-test.js
The stabilized getters PR introduced a regression that caused enumerable symbol properties to not be included when appending. This PR corrects the implementation of append to include symbol property descriptors.
Remerging #23
=> Fix copying symbols

src/semigroup/object.js, src/stable.js, tests/funcadelic-test.js
This fixes the current release of funcadelic which we merged and released today. 10 minutes after we published, we realized that getters should be cached by instance rather than per getter. This PR corrects the wrongs of our ways.
=> We thunk about it and realized that getters should be cached by instance

README.md
I find it easier to see typeclasses and their operations as a table rather than a bullet point list. I formatted the documentation to use a table and added Filterable typeclass.
=> Typeclass table

.babelrc, build.js, package.json, rollup.config.js, tests/funcadelic.test.js, tests/index.js
This PR introduces jest test runner instead of `mocha` & `chai`.
- upgraded to latest babel
- removed mocha & chai
- added jest
- refactored test to match jest
- running tests against built version of funcadelic
=> Replacing mocha & chai in favour of jest

benchmarks/append.js, benchmarks/object-append.js, package.json, scripts/bench.js, scripts/build.js
This PR is adding a `bench` script to allow running benchmarks for funcadelic operations. To run a script, you can call `npm run build && npm run bench <suite-name>`. The benchmark suites are in `benchmarks` directory. I added `object-append` suite as an example. 
When you run a benchmark, it'll generate a report like this,
After this is merged, we can create a quest issue to add benchmarks for all operations that we have.
=> Benchmark setup

scripts/bench.js
This PR adds a column to benchmarks to show how results compare to the top result.
=> Added relative column to bench

README.md
The main thing that makes a semigroup a semigroup is that its operation is associative, so I tried to work that in.
=> Adding example to show SemiGroups are associative

benchmarks/object-map.js, src/functor/object.js
append is a relatively expensive operation. I added benchmarks to show how it compares relative to using other options. 
map with append is 10x slower than using `Object.keys(object).reduce` & mutating descriptor `{}`. This PR changes object map implementation to use the faster method and benchmark file.
=> Refactor Object Functor to make it 10x faster

package.json, src/semigroup/object.js
When debugging microstates in React Native we discovered that
`Object.assign` does not copy over Symbols since React Native is
using their own version of `Object.assign`:
https://github.com/facebook/react-native/blob/master/Libraries/polyfills/Object.es6.js#L12
`extend-shallow` is a popular alternative that supports assigning
Symbols and works in React Native.
=> Use `extend-shallow` instead of `Object.assign` for React Native

benchmarks/object-append.js, package.json, src/semigroup/object.js, tests/funcadelic.test.js
It turns out that `extend-shallow` does not work as expected because it actually defaults to `Object.assign` when available. We need to always use our own implementation of `Object.assign` inside of Object Semigroup to prevent React Native from overwriting our assign with theirs. 
The implementation that I added is just a little slower than `Object.assign`. 
I can get it to be little faster than `Object.assign`, but I need to replace `Object.keys(source).concat(Object.getOwnPropertySymbols(source))` with the following,
```js
function allKeys(o) {
let keys = Object.keys(o), 
keysLength = keys.length,
symbols = Object.getOwnPropertySymbols(o),
symbolsLength = symbols.length,
arr = Array(keysLength + symbolsLength),
totalLength = keysLength + symbolsLength;
for (let j = 0; j < keysLength; …
```
=> Using local assign in Object Semigroup

benchmarks/curry.js, package.json, rollup.config.js, src/applicative.js, tests/funcadelic.test.js
lodash.curry is 2.5KB gzipped. According to my benchmarks, this function is faster than `lodash.curry` too but it doesn't support placeholders which we are not using.
```js
function curry(f) {
return function curried(...t) {
if (t.length === 0) return curried;
if (t.length === f.length) return f(...t);
return curried.bind(this, ...t);
};
}
```
=> Replace lodash.curry with something smaller

src/typeclasses.js, tests/funcadelic.test.js
To address problem described in #46 and #45 this PR will store typeclass symbols on global `Symbol` object. The typeclass will attempt to retrieve the symbol from the global object before creating a new Symbol. This will ensure that all modules will always use one identity for each typeclass.
=> Attach symbols to global

package.json, tests/.eslintrc.json, tests/funcadelic.test.js
Because of the Jest global environment, it really throws off the default eslint style rules, and spews a lot of unnecessary warnings about global variables.
Before:
After:
This adds the jest plugin to whitelist Jest globals as well as the recommended ruleset. It also style checks the tests.
=> Add Jest eslint plugin

README.md, src/chain.js, src/funcadelic.js, tests/chain.test.js
Funcadelic is great for composition, but because of JavaScripts syntax and rightwards associativity, composing a sequence of operations can be awkward. For example, suppose I want to map something, then filter it, then append to it, and then map it again. I'd have to write something like:
```js
let result = map(f2, append(filter(predicate, map(f1, start))))
```
Picking apart the expressions and divining the intent is a difficult task even for the most experienced set of eyes.
With the chain api, you can rewrite the above as:
```js
import { chain as $ } from 'funcadelic';
$(start)
.map(f1)
.filter(predicate)
.append(something)
.map(f2)
.valueOf();
```
Which very clearly describes the sequence of operations.
Each method invocation takes the current value of the chain, applies the …
=> Add support for the chaining API.

CHANGELOG.md, package.json
Also at the same time fixed up older changelog entries to conform to
the spec.
=> Release notes for 0.5.2 which includes chaining api.

src/typeclasses.js, tests/funcadelic.test.js
Turns out naming classes by numbers starting from 0 might not be a
good idea:
```
Unhandled JS Exception: invalid typeclass name: 0
```
So lets use the name & the uniqueTag together to avoid that
=> Add uniqueTag to class name rather than checking for mangling

src/typeclasses.js, tests/funcadelic.test.js
This PR changes how type class instances are registered onto a class prototype to hide type symbol properties from Safari debugger. 
We  want to make sure that Funcadelic plays well with all JavaScript environments. Current implementation adds a lot of noice into the Safari Debugger because the properties are assigned onto the prototype which causes them to be enumerable.
Replace assignment with `Object.defineProperty` and set enumerable to false.
=> Hide typeclass symbols from Safari Debugger

CHANGELOG.md, package.json
- Hide typeclass symbols from Safari Debugger https://github.com/cowboyd/funcadelic.js/pull/65
=> Prepare 0.5.6 release

CHANGELOG.md, src/applicative.js, src/filterable.js, src/foldable.js, src/functor.js, src/monad.js, src/monoid.js, src/semigroup.js
Uglify is an extra eager beaver by stripping off names from functions and classes. This breaks Funcadelic in environments where the developer doesn't have access to Uglify configurations. This is the case with [Razze](https://github.com/jaredpalmer/razzle) as was raised by https://github.com/microstates/microstates.js/issues/342
This PR adds an explicit name to each typeclass so Uglify doesn't strip the name off.
=> Add explicit name to typeclasses

CHANGELOG.md, package.json
- Add explicit name to typeclasses to prevent Uglify from removing the name https://github.com/cowboyd/funcadelic.js/pull/68
=> Updated package.json and CHANGELOG
